import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean.ExponentialFamilyStructure
import HautevilleHouse.CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean.SufficiencyNeymanFisher
import HautevilleHouse.CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean.NeymanPearsonLemma
import HautevilleHouse.CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean.MLEAsymptoticConsistency

namespace HautevilleHouse
namespace CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean

def ConstrainedCharacterizationStructureTheoryStatisticalDistributionsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_characterization_structure_theory_statistical_distributions_endgame (A : AdmissibleClass) :
    ConstrainedCharacterizationStructureTheoryStatisticalDistributionsClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean
end HautevilleHouse