import CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean.Basic

namespace HautevilleHouse
namespace CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean

-- Root module placeholder

end CharacterizationStructureTheoryStatisticalDistributionsTheoremCanonicalLaneLean
end HautevilleHouse